---

## http://docs.ansible.com/ansible/latest/lineinfile_module.html

- name: Remove SABNZBD Container
  docker_container:
    name: sabnzbd
    state: absent

- name: "Set folder permissions"
  shell: "chmod -R 777 /mnt/sab/"

- name: "Set owner permisisons"
  shell: "chown -R 1000:1000 /mnt/sab/"

- name: Create SAB download directory
  file: "path=/mnt/sab/ state=directory mode=0777 owner=1000 group=1000"

- name: Check sabnzbd.ini exists
  stat:
    path: "/opt/appdata/sabnzbd/sabnzbd.ini"
  register: sabnzbd_ini

- name: Deploy SABNZBD Container
  docker_container:
    name: sabnzbd
    image: "linuxserver/sabnzbd"
    pull: yes
#    published_ports:
#      - "8090:8080"
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/sab/complete:/complete
      - /mnt/sab/incomplete:/incomplete
      - /mnt/sab/nzb:/nzb
      - /mnt/sab/admin:/admin
      - /mnt/unionfs:/unionfs
      - /etc/localtime:/etc/localtime:ro
    cpu_shares: 256
    env:
      VIRTUAL_HOST: "sabnzbd.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "sabnzbd.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      PUID: 1000
      PGID: 1000
    restart_policy: always
    state: started
    networks:
      - name: plexguide
        aliases:
          - sabnzbd 

- name: Path for .ini
  wait_for:
    path: "/opt/appdata/sabnzbd/sabnzbd.ini"
    state: present
  when: sabnzbd_ini.stat.exists == False

- name: "Wait 10 Seconds"
  wait_for:
    timeout: 10
  when: sabnzbd_ini.stat.exists == False

- name: Customize sabnzbd_ini
  docker_container:
    name: sabnzbd
    state: stopped
  when: sabnzbd_ini.stat.exists == False

- name: Test
  lineinfile:
    path: "/opt/appdata/sabnzbd/sabnzbd.ini"
    regexp: '^port\s'
    line: 'ports\s'
    state: present
  when: sabnzbd_ini.stat.exists == False

- name: Restart Container
  docker_container:
    name: sabnzbd
    state: started
  when: sabnzbd_ini.stat.exists == False
