########### Original Development of this Script Was Created By desimaniac from https://github.com/desimaniac/Cloudbox

- name: Create nginx-proxy directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /opt/appdata/nginx-proxy

- name: Create and start container
  docker_container:
    name: nginx-proxy
    image: "jwilder/nginx-proxy"
    pull: yes
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/nginx-proxy/dhparam:/etc/nginx/dhparam/"
      - "/opt/appdata/nginx-proxy:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    #command: sh -c "cd /usr/src/app && npm i && npm start"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - name: plexguide
        aliases:
          - nginx-proxy
    restart_policy: always
    state: started

- name: Create and start letsencrypt container
  docker_container:
    name: letsencrypt
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    pull: yes
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/nginx-proxy:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    env:
      DEBUG: true
    networks:
      - name: plexguide
        aliases:
          - letsencrypt
    restart_policy: always
    state: started
